meta:
  environment: sm-mongo-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: mongod
    networks:
      - name: sm_mongo1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: sm_mongo1
  type: manual
  subnets:
  - range: 10.244.147.0/24
    name: sm_mongo1
    gateway: 10.244.147.1
    static:
      - 10.244.147.2 - 10.244.147.60
