jobs:
- name: mongod
  templates:
  - name: mongod
    release: fcf-mongo
  instances: 3
  persistent_disk: 10240
  resource_pool: small_z1
  networks:
  - name: fcf_mongo
    static_ips: (( static_ips(0,1,2) ))

- name: mongodb-broker
  templates:
  - name: cf-mongodb-broker
    release: fcf-mongo
  - name: route_registrar
    release: routing
  instances: 1
  resource_pool: small_z1
  networks:
  - name: fcf_mongo
    static_ips: (( static_ips(3) ))

- name: replset
  templates:
  - name: replset
    release: fcf-mongo
  instances: 1
  lifecycle: errand
  resource_pool: small_z1
  networks:
  - name: fcf_mongo
    static_ips: (( static_ips(4) ))

- name: broker-registrar
  templates:
  - name: broker-registrar
    release: fcf-mongo
  instances: 1
  lifecycle: errand
  resource_pool: small_z1
  networks:
  - name: fcf_mongo
    static_ips: (( static_ips(5) ))

- name: broker-deregistrar
  templates:
  - name: broker-deregistrar
    release: fcf-mongo
  instances: 1
  lifecycle: errand
  resource_pool: small_z1
  networks:
  - name: fcf_mongo
    static_ips: (( static_ips(6) ))
