meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: mongodb
    templates:
    - name: mongodb
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(0) ))
    env:
      MONGODB_USER: (( grab properties.env.MONGODB_USER || "monguser" ))
      MONGODB_PASS: (( grab properties.env.MONGODB_USER || "mongpass" ))
      MONGODB_PORT: (( grab properties.env.MONGODB_PORT || 27017 ))
      MONGODB_DATABASE: (( grab properties.env.MONGODB_DATABASE || "test" ))
      MONGODB_HOST: (( grab jobs.mongodb.networks[0].static_ips[0] ))
      MONGODB_URI: (( concat "mongodb://" jobs.mongodb.env.MONGODB_USER ":" jobs.mongodb.env.MONGODB_PASS "@" jobs.mongodb.env.MONGODB_HOST ":" jobs.mongodb.env.MONGODB_PORT "/" jobs.mongodb.env.MONGODB_DATABASE ))
      net:
        bindIp: 0.0.0.0
      port: (( grab jobs.mongodb.env.MONGODB_PORT ))
      storage:
        dbPath: (( grab properties.env.MONGODB_DBPATH || "/var/vcap/store/mongodb" ))
      systemLog:
        path: (( grab properties.env.MONGODB_SYSTEMLOG || "/var/vcap/sys/log/mongodb/mongodb.log" ))
      keyfile:
        path: (( grab properties.env.MONGODB_KEYFILE || "/var/vcap/jobs/mongodb/config/mongodb-keyfile" ))
      replSet: false
  - name: register-broker
    templates:
    - name: register-broker
    instances: 1
    lifecycle: errand
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(1) ))
  - name: deregister-broker
    templates:
    - name: deregister-broker
    instances: 1
    lifecycle: errand
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(2) ))

properties: {}
